remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: QuickFolders
tagline: Quickly access your five most recent folders — right from your system tray.
description: QuickFolders is a lightweight and modern Windows 11 system tray app that keeps your five most recent folders just one click away.
